import React from 'react'

export default function Contact() {
  return (
    <div>
        <h1>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Adipisci fugiat sequi consectetur velit accusamus, ut iusto molestiae eveniet architecto doloremque asperiores quasi aliquid dignissimos omnis ab qui, sit in nobis tempora, repudiandae praesentium dolore commodi exercitationem deserunt. Nemo nam eaque, asperiores provident expedita tenetur error ex? Recusandae enim repudiandae totam fugiat assumenda dicta veritatis, rerum illum ea saepe ipsum porro, nisi, nobis explicabo possimus incidunt. Obcaecati quae aspernatur neque rerum quo fugiat repellendus esse id maxime. Sunt quisquam recusandae magni distinctio impedit quos ex, dicta aliquam ullam odio amet vel sit saepe rem facilis, officiis explicabo repudiandae! Quisquam, corporis maxime minus reprehenderit obcaecati, maiores ullam accusantium officia tempora ipsa nam consequatur ex eos cupiditate error accusamus recusandae possimus ut, ratione facilis veniam dolor. Delectus quas libero numquam aperiam nesciunt et debitis, aspernatur error? Eveniet excepturi eligendi adipisci ducimus delectus, dignissimos harum. Numquam libero aliquid velit? Eaque iure soluta, recusandae et nesciunt ad laudantium, minus eligendi culpa, amet tempora voluptatem magnam perferendis quas perspiciatis. Sit vero explicabo, vitae ea magni asperiores consectetur voluptatem eveniet fuga, modi ad adipisci, nesciunt consequatur facere at culpa. Quia ullam necessitatibus et in explicabo molestiae officia aperiam cumque! Repellendus eveniet nam accusamus, explicabo distinctio officiis deleniti possimus eligendi ipsa natus dolorem, assumenda praesentium id aliquid. Voluptatem, dicta aspernatur! Error at sit iusto magnam rerum ut numquam, earum nemo exercitationem assumenda, minima asperiores corporis quo! Dicta saepe quam laborum amet iusto ut deserunt maxime sit, minima libero hic et sapiente facere natus ab inventore sed illo sint doloremque in ullam porro vero error. Molestiae ipsam nihil unde quo ab corrupti aut cumque saepe aperiam aspernatur. Temporibus fuga expedita exercitationem aperiam. Repudiandae fuga perspiciatis sunt error, libero debitis? Maxime, eum. Reiciendis vero odit incidunt, corrupti quis iusto nobis laboriosam culpa ad, velit ullam nesciunt quas nulla fuga veritatis?</h1>
    </div>
  )
}
